coverage:
  status:
    project:
      default:
      # setting a very low target so the CI "never" fails
      # I'm more interested in knowing how much is tested
      target: "50"
    patch:
      default:
      # setting a very low target so the CI "never" fails
      # I'm more interested in knowing how much is tested
      target: "50"
comment:
  require_changes: true
