
name: "Test docs build"
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.6
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.6

      - name: Install system deps
        shell: bash
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          build-command: "poetry run invoke docs --no-open-browser --no-serve"
