
name: "Test docs build"
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
