name: Linting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.6
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.6

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
